name: Next.js CI/CD Pipeline

# Trigger the workflow on push to the main or deploy branch
on:
  push:
    branches:
      - main
      - deploy  # Deploy will trigger only on pushes to this branch
  pull_request:
    branches:
      - main

jobs:
  # Job to run code quality checks (ESLint)
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the appropriate version of Node.js for your app
      - name: Install dependencies
        run: |
          npm install
      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx  # Run ESLint to check for code quality issues

  # Job to run unit tests
  run_tests:
    runs-on: ubuntu-latest
    needs: check_code_quality  # Only runs if check_code_quality is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
      - name: Run Jest tests
        run: |
          npm run test  # Replace with your testing script (e.g., Jest)

  # Job to build the Next.js project
  build_project:
    runs-on: ubuntu-latest
    needs: run_tests  # Only runs if run_tests is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
      - name: Build the Next.js app
        run: |
          npm run build  # Runs Next.js build script to optimize and prepare the app for production

  # Job to deploy to Vercel (or another platform like AWS, Heroku, etc.)
  deploy_project:
    runs-on: ubuntu-latest
    needs: build_project  # Only runs if build_project is successful
    if: github.ref == 'refs/heads/deploy'  # Only runs if the push is to the 'deploy' branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npm i -g vercel  # Install Vercel CLI globally
          vercel --prod  # Deploy the Next.js app to Vercel
